spring:
  config:
    import: classpath:project.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=course
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html